name: Generate Snake

on:
  schedule:
    - cron: "0 0 1 1/4 *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: C1B3R123
          outputs: dist/C1B3RS123's GitHub Snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
