name: Generate Data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Generate SVG Snake
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para criar/atualizar a branch output

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Adicionando de volta a etapa para criar o diretório 'dist'
      - name: Create dist directory
        run: mkdir -p dist # Use -p para criar o diretório e subdiretórios se não existirem

      # --- Nova Etapa Simplificada para Garantir a Branch Output Remota ---
      # Esta etapa tenta criar a branch 'output' remotamente se ela não existir
      # Usando uma branch temporária local para um push mais explícito
      - name: Ensure output branch exists remotely
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git branch temp-output
          git checkout temp-output
          git commit --allow-empty -m "Initial commit for output branch"
          git push origin temp-output:refs/heads/output --force
          git checkout main
          git branch -D temp-output
        continue-on-error: true
      # --- Fim da Nova Etapa ---


      - name: Generate snake SVG
        uses: Platane/snk@v3 # Verifique a versão mais recente
        id: snake-svg-orange-dots
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # Removido color_dots, mantido color_snake e sanitize
            dist/github-snake-orange-lightdots.svg?color_snake=#FFA500&palette=github-light&sanitize=true
            dist/github-snake-orange-darkdots.svg?color_snake=#FFA500&palette=github-dark&sanitize=true

      - name: Deploy SVGs to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
