name: Generate Data

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Generate SVG Snake
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate random daily snake color
        id: calculate_color
        run: |
          RANDOM_DECIMAL=$(shuf -i 1-16777214 -n 1)
          RANDOM_HEX=$(printf '%06x\n' "$RANDOM_DECIMAL")
          DAILY_COLOR="#${RANDOM_HEX}"
          echo "DAILY_COLOR=${DAILY_COLOR}" >> $GITHUB_OUTPUT

      - name: Ensure output branch exists remotely
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git branch temp-output
          git checkout temp-output
          git commit --allow-empty -m "Initial commit for output branch"
          git push origin temp-output:refs/heads/output --force
          git checkout main
          git branch -D temp-output
        continue-on-error: true

      - name: Generate snake SVG
        uses: Platane/snk@v3
        id: snake-svg-orange-dots
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-lightdots.svg?color_snake=${{ steps.calculate_color.outputs.DAILY_COLOR }}&palette=github-light&sanitize=true
            dist/github-snake-darkdots.svg?color_snake=${{ steps.calculate_color.outputs.DAILY_COLOR }}&palette=github-dark&sanitize=true

      - name: Deploy SVGs to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
