name: Generate Data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Generate SVG Snake
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para criar/atualizar a branch output

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Adicionando de volta a etapa para criar o diretório 'dist'
      - name: Create dist directory
        run: mkdir -p dist # Use -p para criar o diretório e subdiretórios se não existirem

      # --- Nova Etapa Simplificada para Garantir a Branch Output Remota ---
      # Esta etapa tenta criar a branch 'output' remotamente se ela não existir
      - name: Ensure output branch exists remotely
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Tenta empurrar o commit atual (HEAD) para a branch 'output' no remoto 'origin'
          # --force é usado para garantir que a branch seja criada/atualizada
          git push origin HEAD:refs/heads/output --force
        # Permite que o workflow continue mesmo se este push falhar (ex: branch já existe)
        continue-on-error: true
      # --- Fim da Nova Etapa ---

      - name: Generate snake SVG
        uses: Platane/snk@v3 # Verifique a versão mais recente
        id: snake-svg-orange-dots
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-orange-lightdots.svg?color_snake=#FFA500&color_dots=#ebedf0,#9be9a8,#30c463,#30a1f4,#216e39&sanitize=true
            dist/github-snake-orange-darkdots.svg?color_snake=#FFA500&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353&sanitize=true

      - name: Deploy SVGs to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
