name: Generate Data

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    name: Generate SVG Snake
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake SVG Animation
        uses: Platane/snk@v3 # Verifique a versão mais recente
        id: snake-svg-animation
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-contribution-grid-snake.svg?sanitize=true # Configura a saída como SVG animado
          # Para alguns casos, pode ser necessário ajustar outros parâmetros como svg_out

      - name: Deploy SVG to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist # Agora aponta para o diretório onde o SVG foi gerado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
