name: Generate Data

on:
  schedule:
    - cron: "0 0 27 * *" 
  workflow_dispatch: 
jobs:
  update:
    name: Generate SVG Snake
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        id: snake-svg
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Deploy SVG to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
